### PR TITLE
Renable Keycode file

### PR DESCRIPTION
**Pull request by jvernet**
Use Basilisk_keycodes in src/MacOsX.
It's for a French Macbook keyboard, all key are correctly mapped.

Plus some suggested modification by XCode.

### CODE REVIEW

**Comment by DavidLudwig** [comment]
There is a varied amount of stuff in this pull request, a lot of which does not seem directly related to enabling keycode files.

Which portions of this serve, specifically, to re-enable keycode file(s)?  Is it just commit 7b8beab25a738ced449f7568ea571e3516f870d1 ?  Does it work with the SDL2 backend?

**Comment by jvernet** [comment]
7b8beab is just the keycode file to use for french MacBook keyboard.

34765ae is the key change (re enable reading of keycode pref)
1316b64 is just to remove some warning

Other need to be discarded, I will present another pull request for the 64bits clean build of slirp.

**Comment by DavidLudwig** [comment]
Thanks for the clarification, and thank you for offering to clean up this pull request.

My GitHub "macemu" repo is something that I have been limiting to, for the time being (but maybe not always!), writing an SDL2 backend (for Basilisk II and SheepShaver), one that I'd like to submit as a pull request into cebix's macemu repository.  I am inclined to not merge anything into my repo, that is not related to getting the SDL2 backend working well.

Regarding Slirp, this sounds interesting and potentially good, however, I'm not sure where this fits into my current work on BII + SheepShaver.  It seems to branch away from just, 'get an SDL2 backend working', and more into fixing other issues in BII and SheepShaver.  That's not to say it isn't worth it, but I'm not sure if maintaining a broader, separate fork of BII or SheepShaver, with a broader set of features + changes, is either a good thing, or the right thing.

**Comment by jvernet** [comment]
My changes are related to SDL2: not the same Keycode Files between SDL1 and SDL2 ! Seems that's your build with SDL2 broke the keycode file thing.
I'm also interested by your fork, because there is working XCode project, that are not present in the original Cebix Repo. And that the original Cebix repo seems to be dead.....
Cebix repo is also dead for 64 bit build, a pull request was submitted months ago without any reaction....  
I also found bunch of corrections never merged to cebix, that I'm trying to apply..... I'm also working on a native embedded preference panel and menus, and way to changes disk on the fly inside Basilisk and SShaver...  At least your fork is alive !

**Comment by DavidLudwig** [comment]
Cebix's repo has been regularly getting commits made to it, including a few in the past few days, and several in the past couple of months.

If you have pull requests waiting to be merged, what about asking if anything in particular is holding them up?

For this pull request here, I would much prefer if the changes were limited to the described feature.

Regarding this repository, for now, I am going to limit things to fixes related to developing the SDL2 backend.  At some point, I may expand the repo's scope beyond that, but I am not prepared to do so right now (even if I want to!).

**Comment by rickyzhang82** [comment]
@jvernet 
Regarding to your 64bit clean SLIRP fix, it is better send a separate PR to upstream repo. You can always build it in GNU autotool in Mac OS X and Linux.

Make your PR as small as possible and also relate to one single topic.

**Comment by jvernet** [comment]
Understood, make sense.

May be you can just help me to add slirp  in your SDL2 XCode project I'm using. I tried to add slirp to the XCode project, just as it is done in SheepShaver Project. But got bunch of error, as XCode complain about multiple definitions of this and that. It look's like it use standard tcp.h, socket.h and not those found with slirp.... But it work with the SheepShaver XCode project with same sources....
  The Unix way (make) work !

**Pull request closed without merging**
